title: "Hasnaa Elidrissi"
description: "Data Science & ML Portfolio"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
url: https://HasnaaElidrissi.github.io
baseurl: /HasnaaElidrissi
